name: Publish Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  push_to_registries:
    name: Push Docker image to Github Container Repository
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: create .npmrc file
        run: |
          echo "@benoitquette:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_TOKEN }}" >> .npmrc
          echo "always-auth=true" >> .npmrc

      - run: yarn install

      - run: yarn test

      - name: Build and push Docker image for services
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image for search-basic
        uses: docker/build-push-action@v5
        with:
          file: ./search.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner	 }}/audeets-search-basic:latest
          labels: ${{ steps.meta.outputs.labels }}
